<?php

namespace App\Support;

use Illuminate\Support\Str;

/**
 * Default Terms / Privacy templates. Admins edit them under Admin → Settings → Legal.
 * They are starting points, not legal advice — have them reviewed for your jurisdiction.
 */
class Legal
{
    public static function render(string $doc): string
    {
        $text = (string) (Settings::get('legal_'.$doc) ?: self::template($doc));
        $text = strtr($text, [
            '{company}' => (string) Settings::get('company_name'),
            '{brand}' => Settings::brand(),
            '{email}' => (string) (Settings::get('support_email') ?: 'the support address on our website'),
            '{address}' => (string) (Settings::get('legal_address') ?: '—'),
            '{domain}' => (string) (Settings::get('brand_domain') ?: request()->getHost()),
            '{date}' => now()->toFormattedDateString(),
        ]);

        return Str::markdown($text, ['html_input' => 'escape', 'allow_unsafe_links' => false]);
    }

    public static function template(string $doc): string
    {
        return $doc === 'privacy' ? self::PRIVACY : self::TERMS;
    }

    public const TERMS = <<<'MD'
# Terms of Service

These terms govern your use of {brand} at {domain}, operated by {company} ({address}). By creating an account you agree to them.

## Your account
You must give accurate information and keep your password safe. You're responsible for what happens under your account. You must be old enough to form a binding contract where you live.

## What you build
You own the apps and code you create. You give us permission to host, process and display them only to run the service (for example, to show previews and publish your apps).

## Acceptable use
You may not use {brand} to build or publish anything that is illegal, deceptive or harmful — including phishing pages, malware, scams, spam, content that infringes others' rights, or content that exploits or harms others. We may remove published apps and suspend accounts that break these rules, and anyone can report an app using the "Report" link on it.

## AI output
Code and text are generated by third-party AI models and may contain mistakes. Review what you publish. You're responsible for how you use the output.

## Plans, payments and credits
Paid plans are billed in advance for the period you choose and give you the AI credits listed on the pricing page. Credits reset each month and don't carry over. Unless the law where you live says otherwise, payments are non-refundable. If a paid plan isn't renewed, your account moves to the free plan at the end of the period.

## Availability
We work to keep the service running but don't guarantee it will be uninterrupted or error-free. We may change features with reasonable notice.

## Liability
To the extent the law allows, {company} isn't liable for indirect or consequential losses, and our total liability is limited to the amount you paid us in the 12 months before the claim.

## Ending your account
You can delete your account at any time from Account & security. We may suspend or close accounts that break these terms.

## Changes
We may update these terms. If the changes are significant we'll tell you by email or in the app.

## Contact
{email}

_Last updated {date}._
MD;

    public const PRIVACY = <<<'MD'
# Privacy Policy

{company} ({address}) runs {brand} at {domain} and is responsible for your personal data.

## What we collect
- **Account details:** name, email address, password (stored hashed), and your settings.
- **Your projects:** descriptions, files, chat messages with the AI and published apps.
- **Billing:** plan, payment amounts and references. Card details are handled by our payment providers (Stripe or Paystack) and never reach our servers.
- **Technical data:** IP address and activity logs used for security and troubleshooting.

## Why we use it
To run the service you signed up for (contract), to keep it secure and prevent abuse (legitimate interest), to take payments and keep accounting records (legal obligation), and to email you about your account.

## Who we share it with
- **AI providers** that generate code: the text of your requests and the relevant project files are sent to them to produce answers.
- **Payment providers** to process payments.
- **Email and hosting providers** that run the service for us.

We don't sell your data.

## Cookies
We only use cookies that are needed for the site to work (your sign-in session and security tokens). We don't use advertising or tracking cookies.

## How long we keep it
While your account exists. When you delete your account we delete your profile and projects; we keep payment records as long as tax law requires.

## Your rights
You can download a copy of your data and delete your account at any time from Account & security. Depending on where you live you may also have the right to correct, restrict or object to processing, and to complain to your data protection authority. Contact us at {email}.

## International transfers
Our providers may process data in other countries. Where required, we rely on appropriate safeguards such as standard contractual clauses.

_Last updated {date}._
MD;
}
