<?php

namespace App\Services\Studio;

use App\Models\Project;

/**
 * Generates a working starter app from a project's spec without AI, so the
 * build → preview → publish flow works before a provider is connected.
 */
class Scaffolder
{
    /** @return array<string, string> path => content */
    public static function starter(Project $project): array
    {
        $name = e($project->name);
        $idea = e($project->idea ?: 'Built with AI Code Studio.');
        $features = collect($project->spec['features'] ?? [])->map(fn ($f) => '        <li><span>✓</span>'.e($f).'</li>')->implode("\n");
        $pages = collect($project->spec['pages'] ?? [])->take(5)->map(fn ($p) => '<a href="#">'.e(ucfirst(trim(preg_replace('/[\/\[\]:]+/', ' ', $p)) ?: 'Home')).'</a>')->implode('');

        $html = <<<HTML
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{$name}</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <header class="top">
    <strong class="logo"><span></span>{$name}</strong>
    <nav>{$pages}</nav>
  </header>
  <main>
    <section class="hero">
      <h1>{$name}</h1>
      <p>{$idea}</p>
      <button id="cta">Get started</button>
    </section>
    <section class="card">
      <h2>What’s included</h2>
      <ul class="features">
{$features}
      </ul>
    </section>
    <section class="card">
      <h2>Contact us</h2>
      <form id="contact">
        <input name="email" type="email" placeholder="you@example.com" required>
        <button>Send</button>
      </form>
      <p id="thanks" hidden>Thanks — we’ll be in touch.</p>
    </section>
  </main>
  <script src="app.js"></script>
</body>
</html>

HTML;

        $css = <<<'CSS'
* { box-sizing: border-box; }
body { margin: 0; font-family: system-ui, sans-serif; background: #FAFAF8; color: #1A1A1E; }
.top { display: flex; align-items: center; justify-content: space-between; gap: 16px; padding: 16px 24px; border-bottom: 1px solid #E6E6E2; background: #fff; flex-wrap: wrap; }
.logo { display: flex; align-items: center; gap: 8px; }
.logo span { width: 18px; height: 18px; border-radius: 5px; background: #E0572F; display: inline-block; }
nav { display: flex; gap: 16px; flex-wrap: wrap; }
nav a { color: #66666E; text-decoration: none; }
main { max-width: 960px; margin: 0 auto; padding: 32px 24px 64px; display: flex; flex-direction: column; gap: 20px; }
.hero h1 { font-size: clamp(32px, 6vw, 56px); letter-spacing: -0.03em; margin: 0 0 12px; }
.hero p { color: #55555C; font-size: 18px; line-height: 1.5; max-width: 640px; }
button { height: 40px; padding: 0 18px; border: 0; border-radius: 8px; background: #E0572F; color: #fff; font-weight: 600; cursor: pointer; }
.card { background: #fff; border: 1px solid #E8E8E4; border-radius: 12px; padding: 20px; }
.card h2 { margin: 0 0 12px; font-size: 18px; }
.features { list-style: none; padding: 0; margin: 0; display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 8px; }
.features li { display: flex; gap: 8px; }
.features span { color: #1F7A44; }
form { display: flex; gap: 8px; flex-wrap: wrap; }
input { flex: 1; min-width: 200px; height: 40px; padding: 0 12px; border: 1px solid #E1E1DC; border-radius: 8px; }

CSS;

        $js = <<<'JS'
document.getElementById('cta')?.addEventListener('click', () => {
  document.getElementById('contact')?.scrollIntoView({ behavior: 'smooth' });
});
document.getElementById('contact')?.addEventListener('submit', (e) => {
  e.preventDefault();
  e.target.hidden = true;
  document.getElementById('thanks').hidden = false;
});

JS;

        $readme = "# {$project->name}\n\n{$project->idea}\n\nGenerated by AI Code Studio. Open `index.html` in a browser to run it.\n";

        return ['index.html' => $html, 'styles.css' => $css, 'app.js' => $js, 'README.md' => $readme];
    }
}
